name: Update Site

on:
  schedule:
    - cron: '0 * * * *'  # This example runs the script hourly; adjust as needed.

jobs:
  update-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: R -e "install.packages(c('googlesheets4', 'jsonlite', 'htmltools', 'quarto'))"

      - name: Run script and render site
        run: |
          Rscript -e "source('path/to/your_script.R')"  # Adjust to the path of your script
          quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Adjust to your Quarto output directory
